name: Run Cypress Tests with Allure Reports

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 12 * * 1-5" # 6 AM Monday to Friday in GMT-6 (Colorado Springs)
  workflow_dispatch:
permissions:
  contents: read
  issues: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
        env: [staging]
    name: Run tests in ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Allure reporter and CLI
        run: |
          npm install mocha-allure-reporter --save-dev
          npm install -g allure-commandline --save-dev

      - name: Verify Cypress is installed
        run: npx cypress verify

      - name: Run Cypress tests on ${{ matrix.browser }}
        run: npx cypress run --env version=${{ matrix.env }} --browser ${{ matrix.browser }} --reporter mocha-allure-reporter

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Fail job if tests failed
        if: steps.cypress.outputs.status == 'failed'
        run: exit 1

  generate-report:
    if: always()
    needs: run-tests
    runs-on: ubuntu-latest
    name: Generate merged Allure report

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Combine Allure results
        run: |
          mkdir -p combined-results
          for dir in downloaded-artifacts/*; do
            echo "Processing $dir"
            cp -r "$dir"/* combined-results/ || echo "Nothing to copy from $dir"
          done
          ls -R combined-results || echo "combined-results is empty"

      - name: Generate Allure report
        run: |
          npm install -g allure-commandline
          allure generate combined-results --clean -o allure-report
          ls -R allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/*

  deploy-gh-pages:
    if: always()
    needs: generate-report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages

      - name: Send email with report link
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Allure Report for Cypress Tests"
          to: tmqa2408@gmail.com
          from: Cypress Bot <${{ secrets.EMAIL_USERNAME }}>
          body: >
            <p>Привет!</p>
            <p>Отчет о выполнении автотестов доступен по ссылке:</p>
            <p><a href="https://tmqa2408.github.io/cypress_Cucumber_BDD/">Открыть Allure отчёт</a></p>
            <p>Хорошего дня!</p>
